name: Test
on:
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+.[0-9]+" # release branches
env:
  MICRONAUT_HTTP_SERVICES_ZENDESK_EMAIL: ${{ secrets.MICRONAUT_HTTP_SERVICES_ZENDESK_EMAIL}}
  MICRONAUT_HTTP_SERVICES_ZENDESK_TOKEN: ${{ secrets.MICRONAUT_HTTP_SERVICES_ZENDESK_TOKEN}}
  MICRONAUT_HTTP_SERVICES_ZENDESK_URL: ${{ secrets.MICRONAUT_HTTP_SERVICES_ZENDESK_URL}}
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm-community'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Run Tests # Adapt this command to your testing needs
      run: ./gradlew test